on:
  pull_request: {}
  push:
    branches:
    - main
    - master
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        publishUrl: https://dev.semgrep.dev
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        publishDeployment: 42
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
